// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4919.Robot_2017.subsystems;

import org.usfirst.frc4919.Robot_2017.RobotMap;
import org.usfirst.frc4919.Robot_2017.commands.*;
import edu.wpi.first.wpilibj.Servo;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class CameraControl extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Servo cameraTurner = RobotMap.cameraControlCameraTurner;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new CameraTurner());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        org.usfirst.frc4919.Robot_2017.Robot.cameraControl.cameraTurner.set(0);

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void swapPosition () {
    	Double variable = org.usfirst.frc4919.Robot_2017.Robot.cameraControl.cameraTurner.getPosition();
 
    	if (variable <= 0.5) {
    		org.usfirst.frc4919.Robot_2017.Robot.cameraControl.cameraTurner.set(1.0);
    	}
    	else {
    		org.usfirst.frc4919.Robot_2017.Robot.cameraControl.cameraTurner.set(0);
    	}
    }
}

