// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4919.Robot_2017.subsystems;

import org.usfirst.frc4919.Robot_2017.RobotMap;
import org.usfirst.frc4919.Robot_2017.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GearBoxGate extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Compressor compressor1 = RobotMap.gearBoxGateCompressor1;
    private final DoubleSolenoid gearBoxGateSolenoid1 = RobotMap.gearBoxGateGearBoxGateSolenoid1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void openDoublesolenoid() {
    	gearBoxGateSolenoid1.set(DoubleSolenoid.Value.kForward);
    
    }
    public void closeDoublesolenoid() {
    	gearBoxGateSolenoid1.set(DoubleSolenoid.Value.kReverse);
    	
    }
    public void stop() {
    	gearBoxGateSolenoid1.set(DoubleSolenoid.Value.kOff);
    	
    	
    }
}
